blank_issues_enabled: false
contact_links:
  - name: mydealz Community
    url: https://www.mydealz.de/deals/digitale-adventskalender-und-gewinnspiele-2025-sammeldeal-2687053
    about: Diskussion und weitere Kalender auf mydealz
